function r=solver_rectangular1(result1,j,dt,N1_partition,N2_partition,N1_basis,N2_basis,M_partition,T_partition,M_basis,T_basis,Gauss_coefficient_reference_rectangular,Gauss_point_reference_rectangular,number_of_elements,matrix_size,vector_size,number_of_trial_local_basis,number_of_test_local_basis)

a1=assemble_matrix_from_1_integral_rectangular(result1,j,dt,M_partition,T_partition,T_basis,T_basis,number_of_trial_local_basis,number_of_test_local_basis,number_of_elements,matrix_size,Gauss_coefficient_reference_rectangular,Gauss_point_reference_rectangular,0,0,0,0);
a2=assemble_matrix_from_2_integral_rectangular(result1,j,M_partition,T_partition,T_basis,T_basis,number_of_trial_local_basis,number_of_test_local_basis,number_of_elements,matrix_size,Gauss_coefficient_reference_rectangular,Gauss_point_reference_rectangular,1,0,1,0);
a3=assemble_matrix_from_2_integral_rectangular(result1,j,M_partition,T_partition,T_basis,T_basis,number_of_trial_local_basis,number_of_test_local_basis,number_of_elements,matrix_size,Gauss_coefficient_reference_rectangular,Gauss_point_reference_rectangular,0,1,0,1);
% a4=assemble_matrix_from_3_integral_rectangular(result1,j,M_partition,T_partition,T_basis,T_basis,number_of_trial_local_basis,number_of_test_local_basis,number_of_elements,matrix_size,Gauss_coefficient_reference_rectangular,Gauss_point_reference_rectangular,1,0,0,0);
a5=assemble_matrix_from_3_integral_rectangular(result1,j,M_partition,T_partition,T_basis,T_basis,number_of_trial_local_basis,number_of_test_local_basis,number_of_elements,matrix_size,Gauss_coefficient_reference_rectangular,Gauss_point_reference_rectangular,0,1,0,0);

A=a1+(a2+a3)-a5;
clear  a1 a2 a3 a4 a5

b1=assemble_vector_from_integral_time_rectangular(result1,j,dt,M_partition,T_partition,T_basis,number_of_test_local_basis,number_of_elements,vector_size,Gauss_coefficient_reference_rectangular,Gauss_point_reference_rectangular,0,0);
b=b1;
clear b1 


%Get the information matrices for boundary nodes and boundary edges.
[boundary_nodes,~]=generate_boundary_nodes_edges(N1_basis,N2_basis,N1_partition,N2_partition);


[A,b]=treat_Dirichlet_boundary_rectangular('function_g',A,b,boundary_nodes,M_basis);
r=A\b;







